In [1]:
import os
import numpy as np
import utils
%matplotlib
import matplotlib.pyplot as plt

Using matplotlib backend: Qt5Agg


In [2]:
data_path = os.path.join("..", "..", "..", "AndroidApp","app","src","main","assets","raw_sensor_data", "curls")
gyro_file = "Curls_gyro_sensor_data_1624264514006_original_clipped.csv"
accel_file = "Curls_accel_sensor_data_1624264514006_original_clipped.csv"

In [3]:
gyro_data = np.loadtxt(os.path.join(data_path, gyro_file), delimiter=";")
accel_data = np.loadtxt(os.path.join(data_path, accel_file), delimiter=";")

In [4]:
t_gyro = gyro_data[:,0] # In nanoseconds
t_accel = accel_data[:,0]

In [5]:
T_clip = -1
if (t_gyro[-1] > t_accel[-1]):
    T_clip = t_accel[-1]
else:
    T_clip = t_gyro[-1]
T_clip

1094210574042002.0

In [6]:
T_clip_interval = 4 * 1e9
idx_gyro_clip = np.where(t_gyro < (T_clip - T_clip_interval))[0][-1]
idx_accel_clip = np.where(t_accel < (T_clip - T_clip_interval))[0][-1]

In [7]:
t_gyro_new = t_gyro[idx_gyro_clip:]
t_accel_new = t_accel[idx_accel_clip:]

In [8]:
gyro_data_new = gyro_data[idx_gyro_clip:,:]
accel_data_new = accel_data[idx_accel_clip:,:] 

In [9]:
if gyro_data_new[0,0] > accel_data_new[0,0]:
    t_ref = gyro_data_new[0,0]
else:
    t_ref = accel_data_new[0,0]

In [10]:
t_ref

1094206564211377.0

In [11]:
t_gyro_resampled, gyro_data_resampled = utils.resample_3d_timeseries(gyro_data_new[:,1:], gyro_data_new[:,0], 50 , N_samples = 200, t_ref = t_ref)
t_accel_resampled, accel_data_resampled = utils.resample_3d_timeseries(accel_data_new[:,1:], accel_data_new[:,0], 50 , N_samples = 200, t_ref = t_ref)

In [12]:
t_gyro_resampled[:10] * 1e-9

array([1094206.56421138, 1094206.58421138, 1094206.60421138,
       1094206.62421138, 1094206.64421138, 1094206.66421138,
       1094206.68421138, 1094206.70421138, 1094206.72421138,
       1094206.74421138])

In [13]:
gyro_data[-10:-1,0] * 1e-9

array([1094208.87770101, 1094209.07049122, 1094209.26328226,
       1094209.45607284, 1094209.64886388, 1094209.84165419,
       1094210.03444497, 1094210.22723648, 1094210.420027  ])

In [14]:
plt.figure(figsize=(16,9))
plt.subplot(311)
plt.plot(gyro_data[:,0] * 1e-9, gyro_data[:,1], label="Original")
plt.plot(gyro_data_new[:,0] * 1e-9, gyro_data_new[:,1], label="Original, clipped")
plt.plot(t_gyro_resampled * 1e-9 , gyro_data_resampled[:,0], label="Resampled, clipped", linestyle="--")
plt.grid(which="major")
plt.grid(which="minor", linestyle="--")
plt.minorticks_on()
plt.legend()
plt.title("Gyroscope")

plt.subplot(312)
plt.plot(gyro_data[:,0] * 1e-9, gyro_data[:,2], label="Original")
plt.plot(gyro_data_new[:,0] * 1e-9, gyro_data_new[:,2], label="Original, clipped")
plt.plot(t_gyro_resampled * 1e-9 , gyro_data_resampled[:,1], label="Resampled, clipped", linestyle="--")
plt.grid(which="major")
plt.grid(which="minor", linestyle="--")
plt.minorticks_on()
plt.legend()

plt.subplot(313)
plt.plot(gyro_data[:,0] * 1e-9, gyro_data[:,3], label="Original")
plt.plot(gyro_data_new[:,0] * 1e-9, gyro_data_new[:,3], label="Original, clipped")
plt.plot(t_gyro_resampled * 1e-9 , gyro_data_resampled[:,2], label="Resampled, clipped", linestyle="--")
plt.grid(which="major")
plt.grid(which="minor", linestyle="--")
plt.minorticks_on()
plt.legend()

plt.figure(figsize=(16,9))
plt.subplot(311)
plt.plot(accel_data[:,0] * 1e-9, accel_data[:,1], label="Original")
plt.plot(accel_data_new[:,0] * 1e-9, accel_data_new[:,1], label="Original, clipped")
plt.plot(t_accel_resampled * 1e-9, accel_data_resampled[:,0], label="Resampled, clipped", linestyle="--")
plt.grid(which="major")
plt.grid(which="minor", linestyle="--")
plt.minorticks_on()
plt.legend()
plt.title("Accelerometer")

plt.subplot(312)
plt.plot(accel_data[:,0] * 1e-9, accel_data[:,2], label="Original")
plt.plot(accel_data_new[:,0] * 1e-9, accel_data_new[:,2], label="Original, clipped")
plt.plot(t_accel_resampled * 1e-9, accel_data_resampled[:,1], label="Resampled, clipped", linestyle="--")
plt.grid(which="major")
plt.grid(which="minor", linestyle="--")
plt.minorticks_on()
plt.legend()

plt.subplot(313)
plt.plot(accel_data[:,0] * 1e-9, accel_data[:,3], label="Original")
plt.plot(accel_data_new[:,0] * 1e-9, accel_data_new[:,3], label="Original, clipped")
plt.plot(t_accel_resampled * 1e-9, accel_data_resampled[:,2], label="Resampled, clipped", linestyle="--")
plt.grid(which="major")
plt.grid(which="minor", linestyle="--")
plt.minorticks_on()
plt.legend()

In [16]:
accel_data_resampled[:19, :]

array([[-2.57616815, -1.48292496, -8.52930605],
       [-2.32748294, -1.88435773, -9.42330364],
       [-2.44703916, -1.93311988, -9.70853433],
       [-1.75586815, -2.19496324, -8.90312261],
       [-1.54462692, -2.61707745, -8.41772495],
       [-1.64473777, -3.66885518, -8.37520999],
       [-2.49571976, -4.13225624, -9.26673012],
       [-1.90330457, -4.0265048 , -9.19860745],
       [-1.19835452, -4.08234491, -8.29696874],
       [-1.23641986, -4.67872823, -7.38386978],
       [-1.89990191, -5.32505554, -7.43112078],
       [-1.67055465, -5.72576678, -6.91069352],
       [-1.19307216, -5.96738272, -6.2286356 ],
       [-1.37077078, -6.30035831, -6.24241333],
       [-1.45784397, -6.16628698, -6.6412961 ],
       [-1.05219495, -5.85813744, -6.36340105],
       [-0.77033945, -5.86491763, -5.57366314],
       [-1.61205122, -6.0090991 , -5.63041346],
       [-1.56706193, -5.96033722, -6.23214008]])